variable "env"{}
variable "vpc_cidr_block"{}
variable "default_vpc_id"{}
variable "frontendServers"{}
variable "availability_zone"{}
variable "default_vpc_cidr_block"{}
variable "default_vpc_route_table_id"{}
variable "publicServers"{}
variable "dbServers"{}
variable "backendServers"{}